environment: /ephemeral/mdu/envs/longvideo-habitat
data_root: /ephemeral/mdu/long-video-data/raw/replicacad
dataset_uid: replica_cad_baked_lighting
scene_dataset_config: /ephemeral/mdu/long-video-data/raw/replicacad/replica_cad_baked_lighting/replicaCAD_baked.scene_dataset_config.json
scene_id: Baked_sc1_staging_00
height: 256
width: 256
hfov_degrees: 90
move_speed: 0.5
