#!/usr/bin/env python3
"""Add key-to-query same-chunk RGB-D rows to an existing dataset cache.

The formal run keeps the historical cross-chunk cache intact and appends rows
generated by the current strict key->query geometry contract.  Unit caches are
then rebased from their parent cache, so P1/P2 and P3 consume the same schema.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from concurrent.futures import ProcessPoolExecutor
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from long_video.data.rgbd_memory import build_causal_correspondence_cache


def _path(root: Path, row: dict, key: str) -> Path:
    value = Path(row[key])
    return value if value.is_absolute() else root / value


def _atomic_npz(path: Path, arrays: dict[str, np.ndarray]) -> None:
    temporary = path.with_name(path.name + ".tmp.npz")
    np.savez_compressed(temporary, **arrays)
    os.replace(temporary, path)


def _rebuild_parent(root: Path, row: dict, pixel_stride: int) -> dict:
    destination = _path(root, row, "correspondence_cache")
    temporary = destination.with_name(destination.name + ".intra.npz")
    stats = build_causal_correspondence_cache(
        sorted(_path(root, row, "depth_dir").glob("*.png")),
        np.load(_path(root, row, "c2w_abs")),
        np.load(_path(root, row, "intrinsics")),
        temporary,
        chunk_count=int(row["chunk_count"]),
        pixel_stride=pixel_stride,
        chunk_pairs=[(chunk, chunk) for chunk in range(int(row["chunk_count"]))],
    )
    with np.load(temporary, allow_pickle=False) as value:
        intra = {key: np.ascontiguousarray(value[key]) for key in value.files}
    temporary.unlink()
    with np.load(destination, allow_pickle=False) as value:
        existing = {key: np.ascontiguousarray(value[key]) for key in value.files}
    keep_cross = existing["key_chunk"] != existing["query_chunk"]
    merged = {key: np.concatenate((existing[key][keep_cross], intra[key])) for key in intra}
    _atomic_npz(destination, merged)
    return {"record_id": str(row["record_id"]), "intra_rows": int(stats["row_count"])}


def _rebuild_job(arguments: tuple[Path, dict, int]) -> dict:
    return _rebuild_parent(*arguments)


def _write_unit(root: Path, unit: dict, parent_arrays: dict[str, np.ndarray]) -> None:
    offset = int(unit.get("source_frame_start", 0)); count = int(unit["frame_count"])
    chunk_offset = offset // 32
    keep = (
        (parent_arrays["query_frame"] >= offset) & (parent_arrays["query_frame"] < offset + count)
        & (parent_arrays["key_frame"] >= offset) & (parent_arrays["key_frame"] < offset + count)
        & (parent_arrays["query_chunk"] >= chunk_offset) & (parent_arrays["query_chunk"] < chunk_offset + 3)
        & (parent_arrays["key_chunk"] >= chunk_offset) & (parent_arrays["key_chunk"] < chunk_offset + 3)
    )
    arrays = {key: value[keep].copy() for key, value in parent_arrays.items()}
    arrays["query_frame"] -= offset; arrays["key_frame"] -= offset
    arrays["query_chunk"] -= chunk_offset; arrays["key_chunk"] -= chunk_offset
    _atomic_npz(_path(root, unit, "correspondence_cache"), arrays)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--unified-root", type=Path, required=True)
    parser.add_argument("--pixel-stride", type=int, default=8)
    parser.add_argument("--workers", type=int, default=4)
    args = parser.parse_args()
    root = args.unified_root.resolve()
    all_rows = json.loads((root / "manifest_all.json").read_text(encoding="utf-8"))["records"]
    parents = {str(row["record_id"]): row for row in all_rows if row.get("memory_eligible", True)}
    parent_paths = {record_id: _path(root, row, "correspondence_cache") for record_id, row in parents.items()}
    jobs=((root, row, int(args.pixel_stride)) for row in parents.values())
    with ProcessPoolExecutor(max_workers=max(1, int(args.workers))) as executor:
        for index, stats in enumerate(executor.map(_rebuild_job, jobs), 1):
            print(json.dumps({"completed": index, "total": len(parents), **stats}), flush=True)
    unit_path = root / "manifest_train_units_3chunk.json"
    units = json.loads(unit_path.read_text(encoding="utf-8"))["records"]
    written = 0
    for unit in units:
        parent_id = str(unit.get("parent_record_id", unit["record_id"]))
        if parent_id not in parent_paths:
            raise RuntimeError(f"missing parent cache for unit {unit['record_id']}")
        with np.load(parent_paths[parent_id], allow_pickle=False) as value:
            parent_arrays = {key: np.ascontiguousarray(value[key]) for key in value.files}
        _write_unit(root, unit, parent_arrays); written += 1
    print(json.dumps({"parents": len(parent_paths), "units": written, "schema": "causal-intra-rgbd-v1"}, indent=2), flush=True)


if __name__ == "__main__":
    main()
