#!/usr/bin/env python3
"""Drive M0->M1 validation/reactivation with frames generated by real Helios."""
from __future__ import annotations
import argparse
import json
import sys
import time
from pathlib import Path

import imageio.v2 as imageio
import numpy as np
import torch
from PIL import Image

from long_video.geometry.point_renderer import render
from long_video.initialization.geometry_backend import Pi3GeometryBackend
from long_video.memory.memory_manager import MemoryManager
from long_video.memory.node_builder import build_from_views
from long_video.types import CameraBatch, ViewSet, Z_DEPTH


def load_video(path, count, size):
    reader=imageio.get_reader(str(path))
    frames=[]
    try:
        for frame in reader:
            frames.append(np.asarray(Image.fromarray(frame).resize((size,size),Image.Resampling.BILINEAR)))
            if len(frames)>=count:
                break
    finally:
        reader.close()
    if len(frames)<count:
        raise ValueError(f"need {count} Helios frames, got {len(frames)}")
    return np.stack(frames)


def trajectory(count,size):
    focal=0.5*size/np.tan(np.deg2rad(90.0)/2)
    k=np.repeat(np.array([[focal,0,(size-1)/2],[0,focal,(size-1)/2],[0,0,1]],np.float32)[None],count,axis=0)
    poses=np.repeat(np.eye(4,dtype=np.float32)[None],count,axis=0)
    for index in range(count):
        yaw=0.012*index
        poses[index,:3,:3]=np.array([[np.cos(yaw),0,np.sin(yaw)],[0,1,0],[-np.sin(yaw),0,np.cos(yaw)]],np.float32)
        poses[index,0,3]=0.04*index
        poses[index,2,3]=0.006*index
    return poses,k


def main():
    parser=argparse.ArgumentParser()
    parser.add_argument("--video",type=Path,required=True)
    parser.add_argument("--pi3-repo",type=Path,required=True)
    parser.add_argument("--checkpoint",type=Path,required=True)
    parser.add_argument("--output",type=Path,required=True)
    parser.add_argument("--device",required=True)
    parser.add_argument("--size",type=int,default=128)
    args=parser.parse_args()
    started=time.time(); torch.cuda.reset_peak_memory_stats()
    rgb=load_video(args.video,20,args.size)
    poses,k=trajectory(20,args.size)
    backend=Pi3GeometryBackend(args.checkpoint,args.pi3_repo,device=args.device,input_size=518)
    m0_prediction=backend.predict(rgb[:8],poses[:8],k[:8],known_depth_convention=Z_DEPTH)
    m0_views=ViewSet(
        rgb[:8],m0_prediction.depth,m0_prediction.depth_confidence,poses[:8],k[:8],
        np.full(rgb[:8].shape[:3],2,np.int8),
        np.clip(m0_prediction.depth_confidence*0.5,0,1),
        m0_prediction.depth_convention,
    )
    m0=build_from_views(m0_views,node_id="node_000",voxel_size=0.02,status="active")
    transition_rgb=rgb[8:20]
    cameras=CameraBatch(poses[8:20],k[8:20],args.size,args.size)
    warp=render(m0,cameras,near=0.02,far=8.0,point_radius=0,device=args.device,chunk_points=100000)
    mean_coverage=float(warp.coverage_per_frame.mean())
    manager=MemoryManager(
        geometry_backend=backend,coverage_threshold=min(0.99,mean_coverage+0.05),
        low_coverage_chunks=1,min_transition_frames=12,keyframe_count=8,heldout_count=4,
        min_translation_baseline=2.5,min_view_diversity=float(np.deg2rad(25.0)),
        min_new_area_ratio=0.05,max_world_overlap=0.20,
        max_overlap_rgb_error=0.5,max_overlap_depth_error=1.0,
        reactivation_hysteresis=0.0,
    )
    active,event=manager.process_chunk(m0,transition_rgb,cameras,warp,8)
    promoted=bool(event.get("accepted")) and active.node_id=="node_001"
    revisit_search=None
    if promoted:
        search_poses=[]
        for offset in np.linspace(-1.5,0.2,18):
            pose=poses[0].copy()
            pose[0,3]=float(offset)
            search_poses.append(pose)
        search_poses=np.stack(search_poses)
        search_cameras=CameraBatch(search_poses,np.repeat(k[:1],len(search_poses),axis=0),args.size,args.size)
        parent_warp=render(m0,search_cameras,point_radius=0,device="cpu")
        active_warp=render(active,search_cameras,point_radius=0,device="cpu")
        parent_scores=(parent_warp.visibility*parent_warp.confidence).mean(axis=(1,2))
        active_scores=(active_warp.visibility*active_warp.confidence).mean(axis=(1,2))
        selected=int(np.argmax(parent_scores-active_scores))
        revisit_search={
            "selected_offset":float(search_poses[selected,0,3]),
            "parent_score":float(parent_scores[selected]),
            "active_score":float(active_scores[selected]),
        }
        revisit_cameras=CameraBatch(search_poses[selected:selected+1],k[:1],args.size,args.size)
        revisited,reactivation=manager.maybe_reactivate(active,revisit_cameras)
    else:
        revisited,reactivation=active,None
    result={
        "input_is_real_helios_output":True,
        "video":str(args.video),
        "scale_mode_m0":m0_prediction.scale_info.get("mode"),
        "m0_points":int(len(m0.points_xyz)),
        "transition_mean_coverage":mean_coverage,
        "promotion":promoted,
        "scale_mode_m1":active.scale.mode if promoted else None,
        "candidate_metrics":event.get("metrics"),
        "verified_point_ratio":float(active.quality_metrics.get("verified_point_ratio",0.0)) if promoted else 0.0,
        "reactivation_search":revisit_search,
        "reactivation":reactivation,
        "reactivated_parent":bool(reactivation and revisited.node_id=="node_000"),
        "elapsed_seconds":time.time()-started,
        "peak_gpu_bytes":int(torch.cuda.max_memory_allocated()),
        "gpu_name":torch.cuda.get_device_name(),
    }
    args.output.mkdir(parents=True,exist_ok=True)
    (args.output/"metrics.json").write_text(json.dumps(result,indent=2),encoding="utf-8")
    print(json.dumps(result,indent=2))
    raise SystemExit(0 if result["promotion"] and result["reactivated_parent"] else 1)


if __name__=="__main__":
    main()
